;;; setup-kbds.el  --- KBDS
;;; Commentary:
;;; Globla bindings and rempapings
;;; Code:
(windmove-default-keybindings)
(global-set-key [remap dabbrev-expand] 'hippie-expand)
(global-unset-key (kbd "C-x c"))
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
(global-set-key (kbd "<f1> l") 'counsel-load-library)
(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
(global-set-key (kbd "C-c g") 'counsel-git)
(global-set-key (kbd "C-c j") 'counsel-git-grep)
(global-set-key (kbd "C-c k") 'counsel-ag)
(global-set-key (kbd "C-x l") 'counsel-locate)
(define-key read-expression-map (kbd "C-r") 'counsel-expression-history)
(global-set-key (kbd "C-c m l") 'magit-log-head)
(global-set-key (kbd "C-c m s") 'magit-status)
(global-set-key (kbd "C-c l p") 'package-list-packages)
(global-set-key (kbd "C-;") #'comment-line)
(global-set-key (kbd "C-c j") 'avy-goto-char-timer)
(global-set-key (kbd "C-=") 'er/expand-region)
(global-set-key (kbd "C--") 'er/contract-region)
(global-set-key (kbd "M-g f") 'avy-goto-line)
(global-set-key (kbd "S-C-<down>") 'shrink-window)
(global-set-key (kbd "S-C-<left>") 'shrink-window-horizontally)
(global-set-key (kbd "S-C-<right>") 'enlarge-window-horizontally)
(global-set-key (kbd "S-C-<up>") 'enlarge-window)
(global-set-key (kbd "C-x n") 'neotree-toggle)
 
(provide 'setup-kbds)
;;; setup-kbds.el ends here
